config:
  outputs: |
    [OUTPUT]
        Name cloudwatch_logs
        Match   *
        region eu-west-2
        log_group_name fluent-bit-cloudwatch
        log_stream_prefix from-fluent-bit-
        auto_create_group On
