{{- range $job := .Values.jobs }}
{{- if $job.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $job.serviceAccount.name }}
  labels:
  {{- with $job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
