name: Infracost
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - alb-logs-to-s3-to-cloudwatch
          - api-gateway
          - api-gateway-account-settings
          - aws-alb-to-cloudwatch-lambda
          - aws-cloudfront-security-headers
          - aws-cloudwatch-prometheus-metrics
          - aws-iam-user
          - aws-load-balancer-controller
          - aws-multi-vpc-peering
          - aws-network
          - aws-rds-postgres
          - aws-vpc-peering
          - aws-vpn-vpnendpoint
          - budgets
          - cloudfront-ssl-hsts
          - cloudfront-to-s3-to-cloudwatch
          - cloudfront
          - cloudtrail-s3-to-cloudwatch
          - cloudtrail
          - cloudwatch-alarm-notify 
          - cloudwatch-cross-account-share
          - cloudwatch-log-metric
          - cloudwatch-metrics
          - cloudwatch
          - cognito-identitiy-pool
          - cognito-identity-pool-final
          - cognito-identity
          - cognito-user-pool
          - complete-eks-cluster
          - ecr
          - eks-iam-user-constrain
          - eks
          - elastic-search
          - external-secret-store
          - external-secrets
          - fluent-bit-logs-s3-to-cloudwatch
          - fluent-bit-to-s3
          - fluent-bit
          - goldilocks
          - iam-account-password-policy
          - iam-group
          - ingress
          - metric-filter
          - metrics-filter-multiple
          - metrics-server
          - mongodb-atlas
          - mongodb
          - rabbitmq
          - rds
          - route53-alerts-notify
          - route53
          - s3
          - secret
          - service-alerts
          - sns-cronjob
          - sqs
          - ssl-certificate
          - vpc-flow-logs-to-s3-to-cloudwatch
          - vpc
          - waf
    permissions: write-all
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      - name: Generate Infracost cost estimate baseline
        run: |
          infracost breakdown --path=modules/${{ matrix.path }} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json
        continue-on-error: true

      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Generate Infracost diff
        run: |
          infracost diff --path=modules/${{ matrix.path }}\
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
        continue-on-error: true

      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{github.token}} \
                                     --pull-request=${{github.event.pull_request.number}} \
                                     --behavior=update
        continue-on-error: true
